name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
    steps:
      - name: Debug
        run: |
          echo "GitHub workspace: ${{ github.workspace }}"
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Cargo.toml exists?"
          cat Cargo.toml | head -5
      - name: Install git
        run: apt-get update && apt-get install -y git
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose -- --test-threads=1
